development:
  adapter: postgresql
  encoding: unicode
  database: login-charts_development
  pool: 2

test:
  adapter: postgresql
  encoding: unicode
  database: login-charts_test
  pool: 2
  username: <%= ENV['POSTGRES_USER'] %>

# The production db will pick up the config from $DATABASE_URL in production
